// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRfBOvfUd4tDpWwD0DF3s1WExTiPyAOA',
    appId: '1:1043218848326:web:1674226b82834a3dc88847',
    messagingSenderId: '1043218848326',
    projectId: 'pokecard-tcg',
    authDomain: 'pokecard-tcg.firebaseapp.com',
    storageBucket: 'pokecard-tcg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtU7CMuGX_tqBdRXF_IDkOOYfakxTEn5Y',
    appId: '1:1043218848326:android:ff7e788a1ada89ccc88847',
    messagingSenderId: '1043218848326',
    projectId: 'pokecard-tcg',
    storageBucket: 'pokecard-tcg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV4l6eYH8AJ80eEcQsoqk2bvPeYc7jRJk',
    appId: '1:1043218848326:ios:0b41adda0c2740ebc88847',
    messagingSenderId: '1043218848326',
    projectId: 'pokecard-tcg',
    storageBucket: 'pokecard-tcg.firebasestorage.app',
    androidClientId: '1043218848326-glmoq829qntqfnb00m3ie31btneb1h2o.apps.googleusercontent.com',
    iosClientId: '1043218848326-dde7u5a0o9be562ololhuc058idjlrbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV4l6eYH8AJ80eEcQsoqk2bvPeYc7jRJk',
    appId: '1:1043218848326:ios:139fa54c1164284ec88847',
    messagingSenderId: '1043218848326',
    projectId: 'pokecard-tcg',
    storageBucket: 'pokecard-tcg.firebasestorage.app',
    androidClientId: '1043218848326-glmoq829qntqfnb00m3ie31btneb1h2o.apps.googleusercontent.com',
    iosClientId: '1043218848326-j4idmanvvmmocc57hsap7rif75b4i0il.apps.googleusercontent.com',
    iosBundleId: 'fr.badetitou.pokecardTcg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdRfBOvfUd4tDpWwD0DF3s1WExTiPyAOA',
    appId: '1:1043218848326:web:0b2f552c8e331dc2c88847',
    messagingSenderId: '1043218848326',
    projectId: 'pokecard-tcg',
    authDomain: 'pokecard-tcg.firebaseapp.com',
    storageBucket: 'pokecard-tcg.firebasestorage.app',
  );
}
