# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
    - uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: build/web
        # The committer name and email address
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
